### ISSUE TITLE
期待大佬完善

### ISSUE THREAD

**Issue by DemonRR** [Doone-skser/SSA#1]
期待大佬完善

**Comment by Doone-skser** [comment]
部分接口已经测试完毕可以正式使用了。

**Comment by Alalei2** [comment]
大佬可以预约抢座了吗？

**Comment by DemonRR** [comment]
> 部分接口已经测试完毕可以正式使用了。
那你接口做了个快捷指令 
https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4

**Comment by Doone-skser** [comment]
> 大佬可以预约抢座了吗？

预计2天内会开放

接口已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。

**Comment by Alalei2** [comment]
> > 大佬可以预约抢座了吗？
> 
> 
> 
> 预计2天内会开放
> 
> 
> 
> 接口已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。

谢谢

**Comment by Doone-skser** [comment]
每个学校的不太一样需要微小的调整，正在处理。



| |
sgvfhv
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月12日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Doone-skser/SSA] 期待大佬完善 (Issue #1) |

大佬可以预约抢座了吗？

预计2天内会开放

接口已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。

谢谢

**Comment by Doone-skser** [comment]
公众号预约预计3天后面对新系统全部开放并开源。
