### ISSUE TITLE
抢座出现 “验证失败，请重新验证” 的问题

### ISSUE THREAD

**Issue by 9cats** [Doone-skser/SSA#2]
代码没有更多的改动，只更改了 roomId 和 startTime 等抢座的参数，并确认无误，但是无法抢座。响应如下
```
{'msg': '验证失败，请重新验证', 'success': False}
```
大概看了一下，pageToken 和 token 都获取到了，但是最后还是显示验证失败。个人认为可能是请求参数有缺失，导致需要额外的认证（拖拽验证那种）。
希望大佬能看看，帮~~学渣~~抢个座位  (￣y▽,￣)╭

**Comment by Doone-skser** [comment]
尝试抓包获取submit后面附带的参数，检查backLevel的值是不是有异或者请求的格式有所不同。
如果还没有解决可以添加qq1921868580我帮您测试下。
