### ISSUE TITLE
请问如何部署

### ISSUE THREAD

**Issue by xuxuancheng626** [Doone-skser/SSA#4]

**Comment by KingJin-web** [comment]
可以写一个定时任务

**Comment by xuxuancheng626** [comment]
> 可以写一个定时任务

请问是写个定时任务然后让电脑自动运行这个py文件吗

**Comment by Doone-skser** [comment]
稍后我会把flask版本上传，可以部署在服务器上以使用。

**Comment by KingJin-web** [comment]
![$1)VL1Y55SHX} $Q84Q2@~5](https://user-images.githubusercontent.com/58718905/157439304-4928a2ca-9204-41c1-845a-aba61f988f7c.png)
像这样就行

**Comment by KingJin-web** [comment]
#!/bin/bash
cd /king/python
> python.log
python3 Hello1.py >> python.log
python3 Hello2.py >> python.log
cat  python.log

**Comment by KingJin-web** [comment]
```
#!/bin/bash
cd /king/python
> python.log
python3 SSA.py >> python.log
cat  python.log
```

**Comment by xuxuancheng626** [comment]
> 稍后我会把flask版本上传，可以部署在服务器上以使用。

非常感谢！！！

**Comment by xuxuancheng626** [comment]
> ```
> #!/bin/bash
> cd /king/python
> > python.log
> python3 SSA.py >> python.log
> cat  python.log
> ```

抱歉，我刚接触python，这是在cmd运行的吗，请问您截图的界面是怎么出来的

**Comment by Alalei2** [comment]
> > ```
> 
> > #!/bin/bash
> 
> > cd /king/python
> 
> > > python.log
> 
> > python3 SSA.py >> python.log
> 
> > cat  python.log
> 
> > ```
> 
> 
> 
> 抱歉，我刚接触python，这是在cmd运行的吗，请问您截图的界面是怎么出来的

我也想问下各位大佬🆘

**Comment by Doone-skser** [comment]
> > > 
> > 
> > 
> > > #!/bin/bash
> > 
> > 
> > > cd /king/python
> > 
> > 
> > > > python.log
> > 
> > 
> > > python3 SSA.py >> python.log
> > 
> > 
> > > cat  python.log
> > 
> > 
> > > 
> > 
> > 
> > 抱歉，我刚接触python，这是在cmd运行的吗，请问您截图的界面是怎么出来的
> 
> 我也想问下各位大佬🆘

他这个是部署在linux服务器上的，接口的源码我已经更新上了，windows、macos和linux都可以，需要先pip安装下需要的模块哦。默认端口是12345

**Comment by Doone-skser** [comment]
> > 稍后我会把flask版本上传，可以部署在服务器上以使用。
> 
> 非常感谢！！！

已经上传啦。

**Comment by DemonRR** [comment]
做了个快捷指令可以看一下
https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4

**Comment by Doone-skser** [comment]
> 做了个快捷指令可以看一下 https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4

我已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。

**Comment by xuxuancheng626** [comment]
> > > 稍后我会把flask版本上传，可以部署在服务器上以使用。
> > 
> > 
> > 非常感谢！！！
> 
> 已经上传

**Comment by xuxuancheng626** [comment]
> 做了个快捷指令可以看一下 https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4

感谢！！

**Comment by xuxuancheng626** [comment]
> > 做了个快捷指令可以看一下 https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4
> 
> 我已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。

已关注，请问回复什么获取服务

**Comment by Doone-skser** [comment]
> > > 做了个快捷指令可以看一下 https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4
> > 
> > 
> > 我已经部署在微信公众号上了 可以搜索 杜恩 或者 heydoone 省去多次输入账号的麻烦。
> 
> 已关注，请问回复什么获取服务

请看自述文件

**Comment by Doone-skser** [comment]
> 做了个快捷指令可以看一下 https://www.icloud.com/shortcuts/fc4252f6e3f040fcbcacc034875415d4

刚刚在更新服务器功能，没有及时回复。
