### ISSUE TITLE
房间ID不在服务范围内

### ISSUE THREAD

**Issue by xuxuancheng626** [Doone-skser/SSA#6]
微信公众号中发送预约的信息提示**房间ID不在服务范围内**，请问是房间ID输错还是因为没有到预约时间

**Comment by Doone-skser** [comment]
> 微信公众号中发送预约的信息提示**房间ID不在服务范围内**，请问是房间ID输错还是因为没有到预约时间

目前正处于测试阶段，对房间id的限制将会在测试完毕(预计3日内)后解除。

**Comment by Doone-skser** [comment]
因为学校的图书馆因为疫情关闭了，待开放后测试完毕后再开放哦~

**Comment by asffsafaxsf** [comment]
没开放  我们也测试不了呀 哎

**Comment by Doone-skser** [comment]
> 没开放 我们也测试不了呀 哎
可以联系我qq1921868580 我给您和您的学校添加到测试范围内

**Comment by Cutenewer** [comment]
学习通那种阴间滑动验证码居然可以破解，太强啦。人眼都可能认错。
