### ISSUE TITLE
脚本只预约了一次两个小时就停了

### ISSUE THREAD

**Issue by Tothemoon66** [Doone-skser/SSA#7]

**Comment by Doone-skser** [comment]
有可能存在这几种情况：
- 你的学校不支持连续预约
- 对连续预约有时间间隔要求
- 限制了预约次数
如果排除以上问题，有可能是我后端自动脚本的问题，我会持续关注的。

**Comment by Tothemoon66** [comment]
> 有可能存在这几种情况：
> 
> * 你的学校不支持连续预约
> * 对连续预约有时间间隔要求
> * 限制了预约次数
>   如果排除以上问题，有可能是我后端自动脚本的问题，我会持续关注的。

我刚刚手动试了一下，一个小时一个小时的预约，总共预约了14次仍然可以。至于是否有时间间隔的要求，因为手动预约以及手机延迟等，我不能肯定是不是这个原因

**Comment by Doone-skser** [comment]
> > 有可能存在这几种情况：
> > 
> > * 你的学校不支持连续预约
> > * 对连续预约有时间间隔要求
> > * 限制了预约次数
> >   如果排除以上问题，有可能是我后端自动脚本的问题，我会持续关注的。
> 
> 我刚刚手动试了一下，一个小时一个小时的预约，总共预约了14次仍然可以。至于是否有时间间隔的要求，因为手动预约以及手机延迟等，我不能肯定是不是这个原因

有没有试过2小时2小时的预约，后端是按照2小时来依次预约的。

**Comment by Tothemoon66** [comment]
> > > 有可能存在這幾種情況：
> > > 
> > > * 你的學校不支持連續預約
> > > * 對連續預約有時間間隔要求
> > > * 限制了預約次數
> > >   如果排除以上問題，有可能是我後端自動腳本的問題，我會持續關注的。
> > 
> > 
> > 我剛剛手動試了一下，一個小時一個小時的預約，總共預約了14次仍然可以。 至於是否有時間間隔的要求，因為手動預約以及手機延遲等，我不能肯定是不是這個原因
> 
> 有沒有試過2小時2小時的預約，後端是按照2小時來依次預約的。

刚刚手动试了，两个小时两个小时预约的，总共预约了六次，也都可以

**Comment by Doone-skser** [comment]
我再看看吧，学校图书馆因为疫情关门了，等开门我再看看具体情况。

**Comment by Doone-skser** [comment]
我昨晚发现了一个bug，导致第二次无法预约的问题，今晚你看看应该是可以的~

**Comment by Doone-skser** [comment]
> > > > 有可能存在這幾種情況：
> > > > 
> > > > * 你的學校不支持連續預約
> > > > * 對連續預約有時間間隔要求
> > > > * 限制了預約次數
> > > >   如果排除以上問題，有可能是我後端自動腳本的問題，我會持續關注的。
> > > 
> > > 
> > > 我剛剛手動試了一下，一個小時一個小時的預約，總共預約了14次仍然可以。 至於是否有時間間隔的要求，因為手動預約以及手機延遲等，我不能肯定是不是這個原因
> > 
> > 
> > 有沒有試過2小時2小時的預約，後端是按照2小時來依次預約的。
> 
> 刚刚手动试了，两个小时两个小时预约的，总共预约了六次，也都可以

昨晚能正常预约吗？
